server:
  port: 8070
spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    task:
    scheduling:
      pool:
        size: 10
    properties:
      hibernate:
        format_sql: true
        jdbc:
          minPoolSize: 5
          time_zone: America/Sao_Paulo
        timezone:
          default_storage: NORMALIZE_UTC

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ps-demo
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      
  h2:
   console:
   enabled: true
   path: /h2-console
   