#Configuracao do Server
logging:
  pattern: 
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [X-ReqID=%X{CorrelationId}] [%-5level] [%logger{70}] - %msg%n"

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  api-docs:
    path: "/api-docs"

server:
  port: 8070

spring:
  main:
    banner-mode: "off"   # por algum motivo tem que ser entre aspas duplas
    allow-bean-definition-overriding: true
      
  sql:
    init:
      mode: always
  jpa:
    hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: always
    task:
    scheduling:
      pool:
        size: 10
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          minPoolSize: 5
          time_zone: America/Sao_Paulo
        timezone:
          default_storage: NORMALIZE_UTC

  datasource:
    url: jdbc:postgresql://localhost:5432/db_lanchonete
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    data: data.sql
    initialize: true
    hikari:
      pool-name: ps-demo
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
   