jlapp:
  openapi:
    dev-url: http://localhost:8070
    hom-url: http://localhost:8070
    prod-url: https://localhost:8070

#Configuracao do Server
logging:
  pattern: 
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [X-ReqID=%X{CorrelationId}] [%-5level] [%logger{70}] - %msg%n"

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  api-docs:
    path: "/api-docs"

server:
  port: 8070

spring:
  devtools:
    add-properties: false
  sql:
    init:
      mode: always
  main:
    banner-mode: "CONSOLE"   # por algum motivo tem que ser entre aspas duplas
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    defer-datasource-initialization: true
    task:
    scheduling:
      pool:
        size: 10
    properties:
      hibernate:
        format_sql: true
        jdbc:
          minPoolSize: 5
          time_zone: America/Sao_Paulo
        timezone:
          default_storage: NORMALIZE_UTC
          

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    data: data.sql
    hikari:
      pool-name: ps-demo
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      
  h2:
   console:
     enabled: true
   path: /h2-console
