apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlapp-deployment
spec:
  selector:
    matchLabels:
      app: jlapp
  replicas: 1
  template:
    metadata:
      labels:
        app: jlapp
    spec:
      containers:
      - name: jlapp
        image: jlapp_local:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8070
        resources:
          requests:
            cpu: 600m
            memory: 756Mi
          limits:
            cpu: 1000m
            memory: 1536Mi
        env:
          - name: JAVA_OPTS
            value: "-server -Xmx1536M -Xms756M -Xss128m -XX:+UseParallelGC -XX:MaxRAMPercentage=75 -XX:ActiveProcessorCount=2 -XX:+UnlockExperimentalVMOptions"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/db_lanchonete
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
