apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlapp-deployment
spec:
  selector:
    matchLabels:
      app: jlapp
  replicas: 1
  template:
    metadata:
      labels:
        app: jlapp
    spec:
      containers:
      - name: jlapp
        image: jlapp_local:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8070
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/db_lanchonete
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
