name: Deploy to AWS EKS

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EKS
        uses: giovannirossini/aws-eks-kubectl-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          cluster-name: 'jlapp-cluster'
          command: |
            kubectl apply -f k8s/DB
            kubectl apply -f k8s/
            kubectl apply -f k8s/Metrics