name: Implantar no AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  create_elastic_beanstalk:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar e configurar AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Criar aplicação Elastic Beanstalk
        run: aws elasticbeanstalk create-application --application-name jlapp

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Configurar JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20

      - name: Construir com Maven
        run: mvn clean install

      - name: Implantar no AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: jlapp
          environment_name: jlapp-prod
          version_label: ${{ github.run_id }}
          deployment_package: target/jlapp-0.0.1-SNAPSHOT.jar
