name: Deploy to AWS EKS

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install and configure AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name jlapp-cluster

      - name: Deploy Database
        run: |
          kubectl apply -f k8s/DB
      - name: Deploy Service
        run: |
          kubectl apply -f k8s/
      - name: Deploy Metrics
        run: |
          kubectl apply -f k8s/Metrics